### ISSUE TITLE
Chybné volání bootstrap.end.php

### ISSUE THREAD

**Issue by petrleocompel** [err0rmaker/Pocty#2]
bootstrap.end.php by měl být volán pouze v aplikačních souborech na konci nikoliv ve View

> View je pouze zobrazovací (neobsahuje logiku jen renderuje data)
> Controller - obsahuje logiku a posílá data do View - a na konci by měl zavřít připojení do db pokud není spuštěn někde výše

Controllery jsou pro tebe index.php, login.php, atd... (soubory v kořenu projektu, které volá uživatel)

Doporučeno přemístit z view do controllerů.

**Comment by karelSoupa** [comment]
Opraveno
